#+TITLE: ./

#+BEGIN_EXPORT html
<pre>
<code>> ./index.html</code>
</pre>
#+END_EXPORT

[[https://hnvy.github.io/about.html][About]] - [[https://hnvy.github.io/archive.html][Archive]] - [[https://hnvy.github.io/rss.xml][RSS feed]]

[[https://github.com/hnvy/hnvy.github.io/edit/main/src/index.org][ESotP]]

-----

* hnvy.github.io
:PROPERTIES:
:CUSTOM_ID: hnvy
:END:
This site is for me to document my thoughts, ideas, and progress. It is composed of nothing but HTML and a (very) simple CSS. No Javascript, no analytics, no cookies, no advertisement, no nothing. Just text and, sometimes, pictures. Think of it as a personal Wiki of a young learner...

* Edit Something on this Page (ESoTP)
:PROPERTIES:
:CUSTOM_ID: esotp
:END:
This website exists solely to demonstrate that being a novice is perfectly OK, and that novices make mistakes (lots of them). Every page on this site will have a hyperlink, at the top, to allow you to Edit Something on this Page (ESoTP). This is a call to action for you to identify any errors (and, I do mean /any/ errors) in my work, fix them, and send a pull requests.

* Subdomains
:PROPERTIES:
:CUSTOM_ID: subdomains
:END:
I converted the content of the site to Org mode files to reduce the maintenance friction. The Org mode files are then converted to HTML. Have a look at the source code below to find out more about the process.
| Name           | Source code |
|----------------+-------------|
| [[https://hnvy.github.io/][hnvy.github.io]] | [[https://github.com/hnvy/hnvy.github.io][GitHub]]      |
| [[https://hnvy.github.io/blog-1/][blog-1]]         | [[https://github.com/hnvy/blog-1][GitHub]]      |


#+BEGIN_EXPORT html
<p>
<hr style="width:75%;">
</p>

<footer style="font-size: 0.75em; font-style: italic; text-align: center; margin-left: auto; margin-right: auto;">
<p>Unless otherwise noted, every original piece of writing, artwork, and code snippet on <a href="https://hnvy.github.io/">this site</a> is licensed under <a href="https://www.gnu.org/licenses/gpl-3.0.html">GPLv3+</a>.</p>

<p>Please note that the content on this site is NOT intended to be used as a diagnostic or treatment tool. If you are having any symptoms, you should always seek professional medical attention. My notes are NOT intended to be medical advice; you should seek guidance from your physician rather than the internet. Once again, this document is NOT for medical advice! In fact, NONE of this site's information should be taken as advice, because the content on this site may NOT be applicable to you.</p>
</footer>
#+END_EXPORT
