# This is taken from System Crafters: https://systemcrafters.net/publishing-websites-with-org-mode/automated-site-publishing/

name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

# jobs:
  # publish:
    # runs-on: ubuntu-latest
    # steps:
      # - name: Checkout
        # uses: actions/checkout@v2

      # - name: Install Emacs
        # run: sudo apt install emacs-nox --yes

      # - name: Change permission of script.sh
        # run: chmod +x script.sh

      # - name: Build the site
        # run: ./script.sh

      # - name: Publish generated content to GitHub Pages branch
        # uses: JamesIves/github-pages-deploy-action@v4
        # with:
          # branch: gh-pages
          # commit-message: Update ${{ github.sha }}
          # folder: public
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Emacs
        uses: jcs090218/setup-emacs-windows@master
        with:
          version: 24.5
            
      - name: Build the site
        run: emacs -Q --script org-publish.el


  deploy:
    concurrency: ci-${{ github.ref }}
    needs: [build] # The second job must depend on the first one to complete before running and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifacts # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v1
        with:
          name: site

      - name: Publish generated content to GitHub Pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          commit-message: Update ${{ github.sha }}
          folder: public
