name: Publish modified content to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch 0 commits

      # The following will create this folder structure: ./copy/src
      # The folder structure above will simulate the current working directory.
      # This will allow us to publish the files to the correct folders (via ~xargs -I{} cp --parents {} ./copy/~).
      - name: ./copy/src creation and copying
        run: |
          mkdir -p copy/src
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs -I{} cp --parents {} ./copy/

      - name: Install Emacs
        run: sudo add-apt-repository ppa:kelleyk/emacs && sudo apt-get update && sudo apt install emacs28-nox

      - name: Publish modified files only
        run: emacs -Q --script org-publish.el

      - name: Publish generated content to GitHub Pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          clean: false # Do not overwrite/delete the old files. This is because, from now on, we will only publish the changed files.
          commit-message: Update ${{ github.sha }}
          folder: public
